### ISSUE TITLE
Формирование окружения разработчика

### ISSUE THREAD

**Issue by alehinsasha** [o-homyak/finaltask#1]
- [x] Внешние отчеты и обработки разбираются на исходники
- [x] Структура каталогов репозитория из bootstrap

**Comment by o-homyak** [comment]
Формирование окружения разработчика:
 - я вот честно не понимаю, что тут сделать. Окружение у нас уже сделано поскольку мы установили весь необходимый софт уже себе на компьютеры. Мне надо описать это?

Ну исходя из ДЗ у меня имеется скрипт по настройке репозитария.  Надо его применить и в комитах описать?

**Comment by alehinsasha** [comment]
**Внешние отчеты и обработки разбираются на исходники**

Опять же, реализуйте задачу финального задания, учитывая эти issue. А проверять я буду по коммитам и по содержанию этого (внешнего) репозитория.

Т.е. (например) завтра в первой половине дня или сегодня ночью (не знаю когда будет время) проверяя репозитории финалистов, зайду в ваш репо финального задания, увижу каталог **src** а в нем исходники обработки и пойму что окружение у вас настроено - соответственно поставлю флаг.

а так же если у вас будет в репозитории каталог **features** и каталог **tools** а в нем обработка ВыгрузкаЗагрузкаДанных.xml, то я пойму что вы по bootstrap организовали структуру и наименования каталогов в вашем локальном репо, а так же умеете использовать фикстуры, но это уже в другом issue.

**Comment by o-homyak** [comment]
Создал структуру каталогов скриптом. Потому как вываливает ошибку при получении репозитария.

https://xdd.silverbulleters.org/uploads/default/original/1X/334b3e0ee6a8a6baf4baba6d7c3b6b46dd72429a.png

**Comment by alehinsasha** [comment]
готово
