### ISSUE TITLE
Разработка по промышленным стандартам

### ISSUE THREAD

**Issue by alehinsasha** [o-homyak/finaltask#3]
- [x] Одна функциональность = одна фича и сценарии проверяющие работу этой фичи/функциональности
- [x] Использование фикстур
- [ ] Повторное использование шагов (собственная библиотека шагов)
- [x] Фичи из воздуха
- [x] Детализация фичи

**Comment by alehinsasha** [comment]
**В дополнение к проверке навыка "Повторное использование шагов (собственная библиотека шагов)"**

Для подтверждения этого навыка у вас должно быть:
1. Две фичи проверяющие поступление и продажу товара.
2. В каталоге features каталог в котором вы будете хранить ваши библиотечные фичи.
3. В этом каталоге библиотечных шагов должна быть одна фича с одним универсальным (параметризованным) шагом который будет удалять документы.
4. В фичах поступления и продажи нужно использовать этот библиотечный шаг.

**Comment by o-homyak** [comment]
Одна функциональность = одна фича и сценарии проверяющие работу этой фичи/функциональности

К примеру какую фичу порекомендуете создать? Точнее, какой сценарий ее действия?.

**Comment by alehinsasha** [comment]
> Одна функциональность = одна фича и сценарии проверяющие работу этой фичи/функциональности

тут проверяется, что в одной фиче проверяеться одна функциональность. На практике были случаи когда в одной фиче больше одной функциональности проверялось. Например, у одного клиента разработчик проверял в одной фиче регистрацию некоего события в регистре сведений и в той же фиче проверял срабатывание и результат работы регламентного задания отправляющего событие куда-то во вне.

> Просто в данном случае результатом этой фичи будет просто пример действия пользователя как выбрать товар и провести документ.

Да, вполне годиться, функциональность - проведение документа, а дальше в сценариях: по какому регистру, с какими особенностями и т.д.

**Comment by o-homyak** [comment]
Падаю, помогите разобратся:. Делал шаг в шаг по видео. Запустил тест клиент, записал воспроизводимые шаги и начал помещать их к себе. Почему-то падает покнопке добавить. Данная кнопка является платформенной табличной части.

05.10.2016 18:47:57 {ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(1659)}: Ошибка при вызове метода контекста (Нажать): Метод не может быть вызван для данного объекта (Добавить): Метод не может быть вызван для данного объекта (Добавить); ИмяФайла=d:\gitrepo\vanessa-behavior\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf, ИмяПроцедуры=ВОткрытойФормеВТЧЯНажимаюНаКнопку, версия VB=ver 1.035

до этого прошли шаги успешно  и выбрался контрагент в шапку.
Вот сценарий фичи:

Сценарий: Покупка товаров 
	Допустим я подготавливаю процес закупки
	Когда я создаю покупку 
		Когда В панели разделов я выбираю "Закупки"
		И     В панели функций я выбираю "Покупка"
		Тогда открылось окно "Покупка"
		И     я нажимаю на кнопку "Создать"
		Тогда открылось окно "Покупка (создание)"
	
	И я заполняю шапку документа
		И     я открываю выпадающий список "Поставщик"
		И     я выбираю значение реквизита "Поставщик" из формы списка
		Тогда открылось окно "Контрагенты"
		И     В форме "Контрагенты" в таблице "Список" я перехожу к строке:
		| 'Наименование'       |
		| 'Основной поставщик' |
		И     я нажимаю на кнопку "Выбрать"
	
	И я выбираю товары
		И     в ТЧ "Товары" я нажимаю на кнопку "Добавить"
		И     в ТЧ "Товары" я выбираю значение реквизита "Товар" из формы списка
		Тогда открылось окно "Товары"
		И     В форме "Товары" в таблице "Список" я перехожу к строке:
		| 'Код'        | 'Наименование'         |
		| '0000000001' | 'Спининг одноколенный' |
		И     В форме "Товары" в ТЧ "Список" я выбираю текущую строку
		Тогда открылось окно "Покупка (создание) *"

**Comment by o-homyak** [comment]
Вопрос снят.

**Comment by o-homyak** [comment]
не могу разобраться, что не так*?

**Comment by alehinsasha** [comment]
Ок, чуть позже посмотрю. Подождите.

**Comment by o-homyak** [comment]
Кстати как-то странно клиенсткое дейтсвие между видео и моим клиентом отличается, 

а именно в видео: И     в открытой форме в ТЧ "Товары" я нажимаю на кнопку "Добавить"
у меня: И    в ТЧ "Товары" я нажимаю на кнопку "Добавить"

пробовал добавлять "в открытой форме ", все так-же.

М.б. релиз платформы я использую последний 1С:Предприятие 8.3 (8.3.9.1818)

**Comment by alehinsasha** [comment]
> Кстати как-то странно клиенсткое дейтсвие между видео и моим клиентом отличается,
> 
> а именно в видео: И в открытой форме в ТЧ "Товары" я нажимаю на кнопку "Добавить"
> у меня: И в ТЧ "Товары" я нажимаю на кнопку "Добавить"

Леонид мог изменить библиотечный шаг.

> Падаю, помогите разобратся.

А вы закоммитили это? Т.е. если состояние конфигурации, фич и обработок проверки закоммичено и отправлено сюда (во внешний репо) я мог бы выкачать себе ваш репо и посмотреть в чем проблема. Только мне нужна будет конфигурация, а ее нужно выгрузить в исходники в \src\cf, как описано в #5. Пока вы отвечаете, выкачаю ваш репо и попробую воспроизвести ошибку.

**Comment by o-homyak** [comment]
Вы специально закрыли ветку? просто я еще недоделал задания.

**Comment by alehinsasha** [comment]
**я не закрывал**

![image](https://cloud.githubusercontent.com/assets/8247178/19149110/e9274130-8bc8-11e6-846b-216c5a43818c.png)

**Comment by o-homyak** [comment]
О как... я думаю, что это за значок такой, но странно как я умудрился его закрыть.

**Comment by o-homyak** [comment]
Промахнулся с кнопкой... Переоткрываю.

**Comment by alehinsasha** [comment]
возможно по несторожности "Close and comment" нажали, со всеми бывает

**Comment by o-homyak** [comment]
Ну вот не зрая в умных книжках говорится, что нельзя называть кнопки одноименно.... Особенно если они кардинально делают абсолютно разное. И на тебе, где-где, а на гитхабе такая вот несуразица.

**Comment by o-homyak** [comment]
Возможно понадобится удаленное подключение к моей машинке, всячески готов помочь.

**Comment by alehinsasha** [comment]
Ошибка воспроизвелась, разбираюсь.

**Comment by o-homyak** [comment]
Вот я сразу навожу ваше внимание на такую деталь как:
а именно в видео: И в открытой форме в ТЧ "Товары" я нажимаю на кнопку "Добавить"
у меня: И в ТЧ "Товары" я нажимаю на кнопку "Добавить"

Скорей всего разработчики 1С, что-то видоизменили в автоматизированном тестировании в новом релизе платформы.

**Comment by alehinsasha** [comment]
**Решение**

Вариант 1: вместо `И     в ТЧ "Товары" я нажимаю на кнопку "Добавить"` использовать `И     в открытой форме в ТЧ "Товары" я нажимаю на кнопку с именем "ТоварыДобавить"`.

Вариант 2: сделать pull request с изменением алгоритма (не пугайтесь, я сам сделаю, но ошибка не воспроизводиться на 8.3.8, т.е. это не задокументированные изменения автоматизированного тестирования со стороны 1С). Дело в том что в клиенте тестирования (в программной реализации работы с ним) у табличной части есть кнопки и это кнопки контекстного меню (внезапно) их можно получить и но нажатие на кнопку, получается, контекстного меню вызывает ошибку. Но так же у табличной части есть командная панель у которой есть кнопки, уже не контекстные, а нормальные (видимые) и вот если на эти кнопки нажимать то ошибки не будет.

Можно увидеть разницу на скриншотах (обратите внимание, что вид кнопки один и тот же и только по имени можно различить...):

**Кнопка контекстного меню**

![image](https://cloud.githubusercontent.com/assets/8247178/19155530/77cbabe2-8be7-11e6-84e4-032e7dcddf45.png)

**Обычная кнопка**

![image](https://cloud.githubusercontent.com/assets/8247178/19155541/837f69f6-8be7-11e6-98f7-330d13a9e28c.png)

В общем советую первый вариант, это то же библиотечный шаг, но просто по умолчанию при "накнопывании" сценария (во время записи действий пользователя) берется шаг поиска по заголовку. Первый вариант, потому что pull request будет проверяться на разных версих платформы, а это время и нет уверенности что на всех версиях будет корректно работать.

**Comment by alehinsasha** [comment]
> Вот я сразу навожу ваше внимание на такую деталь как:
> а именно в видео: И в открытой форме в ТЧ "Товары" я нажимаю на кнопку "Добавить"
> у меня: И в ТЧ "Товары" я нажимаю на кнопку "Добавить"

смотрите какое дело, шаг `И в открытой форме в ТЧ "Товары" я нажимаю на кнопку "Добавить"` и шаг `И в ТЧ "Товары" я нажимаю на кнопку "Добавить"` был автоматически сгенерирован алгоритмом который написал Леонид Паутов. Т.е. не в этом дело. Советую позже посмотреть ещё раз начало четвертого блока учебных материалов, ту часть что про автоматизированое тестирование. Хотя в #4 мы об этом поговорим.

**Comment by alehinsasha** [comment]
[pull request](https://github.com/silverbulleters/vanessa-behavior/pull/410) сделал!

**Comment by o-homyak** [comment]
Заработало. Буду сооружать фичу.

**Comment by o-homyak** [comment]
На видео автор обходит звездочкой, но в даном случае меня интересует регистратор именно Покупка. Как проверить?

06.10.2016 23:01:17 {ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(2338)}: ТЧ Список. Строка № 1. Колонка Регистратор. Ожидали Покупка *, а получили Покупка 7 от 06.10.2016 23:01:15; ИмяФайла=d:\gitrepo\vanessa-behavior\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf, ИмяПроцедуры=ТаблицаФормыСИменемСталаРавной, версия VB=ver 1.037

**Comment by o-homyak** [comment]
Насчет повторного использования шагов не совсем понял. В видео мелком это говорится, что снипеты автоматически будут подставлены.

**Comment by o-homyak** [comment]
И я вот еще не понял как удалить документ в шаге. Непонял, как именно этот документ найти ведь мы его только . что создали. Или мы будем удалять все документы?

**Comment by alehinsasha** [comment]
> На видео автор обходит звездочкой, но в даном случае меня интересует регистратор именно Покупка. Как проверить?

попробую у себя воспроизвести

> И я вот еще не понял как удалить документ в шаге. Непонял, как именно этот документ найти ведь мы его только . что создали. Или мы будем удалять все документы?
> В текущей фиче я пытаюсь установить пометку на документы под номерами 1

самый простой вариант в фиче указывать дату документа (или номер), а потом или до создания фичи искать и удалять документы за день или по номеру.

**Если на другой стороне придуманного вами варианта проверки функциональности (я не только удаление документов имею в виду) будет рабочая функциональность, никто не имеет права вам говорить что что-то не так. Методология только прививаеться миру 1С, так что творите смелее, это все тот же 1С)))**

**Comment by o-homyak** [comment]
я все уже закомитил. Решения впринципе сделаны по задаче. Повторный шаг я использую.

Но вопросы остались:

Как в фичу передать номер документа, который только что создался?

Как в проверке регистратора проверить на вид документа. Иначе он не работает тоесть Покупка * будет ошибку давать. Надо просто *. Но в таком случае я не убеждаю в сценарии, что я проверил именно поступление. Да я в шаге пользую список покупки. Но это может быть журнал с составными типами и тогда вопрос встанет о крректности проверки уже актуален?

**Comment by alehinsasha** [comment]
> Как в фичу передать номер документа, который только что создался?

вы же в фиче в шаге (фичи из воздуха) можете присвоить номер документу. Например:

```
# ваш, самописный шаг
И Я удаляю все документы вида "Приход" с номером "0000055"
# шаги полученые в результате записи действий пользователя
И Я создаю документ
И Я в поле "Номер" пишу "0000055"
```

> Как в проверке регистратора проверить на вид документа. Иначе он не работает тоесть Покупка * будет ошибку давать. Надо просто *. Но в таком случае я не убеждаю в сценарии, что я проверил именно поступление. Да я в шаге пользую список покупки. Но это может быть журнал с составными типами и тогда вопрос встанет о крректности проверки уже актуален?

надо фичу смотреть, сейчас выкачаю - посмотрю.

**Comment by alehinsasha** [comment]
К сожалению ошибка не воспроизвелась. Обычно, чтобы не проверять всю строку целиком пишут "Покупка *". Не получается так?

**Comment by alehinsasha** [comment]
Думаю эту задачу, можно закрыть, т.к. навык вы подтвердили.
