### ISSUE TITLE
Программная работа с функциональностью "Автоматизированное тестирование 1С"

### ISSUE THREAD

**Issue by alehinsasha** [o-homyak/finaltask#4]
- [ ] Создать свой шаг проверяющий текст сообщения пользователю

**Comment by alehinsasha** [comment]
**В дополнение к проверке навыка "Создать свой шаг проверяющий текст предупреждения"**

Нужно реализовать свой шаг используя функциональность "Автоматизированное тестирование 1С" и свойство "ТестовоПриложение" переменной "КонтекстСохраняемый", который проверяет сообщения пользователю в момент проведения документа реализации товара. Например, если нет в сообщении текста "Не хватает товара" то реализация провелясь корректно. Или если есть текст "Не хватает товара" а товара действительно нет на остатках, то - Ок, функциональность контроля остатков проверена.

**Comment by o-homyak** [comment]
А можно направить, в каком месте я упустил наводящий момент в видео, чтобы все сначала не пересматривать?

**Comment by alehinsasha** [comment]
Ок!

Допустим вы написали фичу
И в фиче один шаг
И в процедуре проверки шага вы используете `КонтекстСохраняемый.ТестовоеПриложение`
И в синтакс-помощнике вы находите метод получающий сообщения пользователю из клиента тестирования
А так же вам понадобиться контекст с подключением клиента тестирования
И ещё шаги, которые воспроизводят действия пользователя приводящие к появлению сообщения пользователю

Например: можно через сообщения проверить контроль отрицательных остатков при проведении реализации.

**Comment by o-homyak** [comment]
Ну что-же буду эксперементировать.

**Comment by alehinsasha** [comment]
Пишите, если что...

**Comment by alehinsasha** [comment]
Если будут проблемы - коммитьте, чтобы я мог у себя воспроизвести.

**Comment by o-homyak** [comment]
Не получается найти используемый метод. Я шаги проведения воспроизвел вот ловлю точку останова и пытаюсь как-то получить текст сообщения - не получается.
![image](https://cloud.githubusercontent.com/assets/22451916/19198128/193e7214-8cc6-11e6-8509-49b91081938d.png)

**Comment by o-homyak** [comment]
Вопрос - снят. Разобрался.

**Comment by alehinsasha** [comment]
Отлично!
