### ISSUE TITLE
Сообщить данные для получения сертификата финалиста

### ISSUE THREAD

**Issue by alehinsasha** [o-homyak/finaltask#6]
В комментарии к этому issue напишите ваши:

* Имя Фамилию (в дательном падеже)
* Адрес электронной почты, на которую выслать сертификат

**Comment by o-homyak** [comment]
Хомяку Александру Николаевичу

e-mail: oleksandrhomyak@gmail.com

**Comment by alehinsasha** [comment]
Успехов, Александр! Вы молодец!
